sudo: required
services:
    - docker

before_install:
    - docker build -t sampetrie/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run sampetrie/react-test npm test -- --coverage

after_success:
    # build images for each part of the project
    - docker build -t sampetrie/multi-client ./client
    - docker build -t sampetrie/multi-nginx ./nginx
    - docker build -t sampetrie/multi-server ./server
    - docker build -t sampetrie/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login - u "$DOCKER_ID" --password-stdin
    # take images and push them to docker hub
    - docker push sampetrie/multi-client
    - docker push sampetrie/multi-nginx
    - docker push sampetrie/multi-server
    - docker push sampetrie/multi-worker